import Adafruit_CharLCD as LCD
import time
import sys

lcd = LCD.Adafruit_CharLCDBackpack(address=0x21) # Here we define the lcd address. It might not be 0x21 but it might be
speed = 0.5 # Manage the scrolling speed of the text. .5 is really good but you can speed it up by decreasing the value and vice versa
def splash(): # Custom start splash. Customise it as you like 
    lcd.set_backlight(0)
    lcd.message("Suzuka Corp.")
    lcd.set_cursor(0, 1)
    lcd.message("(c) 2026")
    time.sleep(2)
    lcd.clear()
    
def motd(): # Now unused defunct version of the motd.
    while True:
        try:
            lcd.clear()
            lcd.set_backlight(0)
            lcd.message("T".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("To".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Tod".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Toda".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today'".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's ".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's a".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's an".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's ani".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anim".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime ".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime i".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime in".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("oday's anime inc")
            time.sleep(speed)
            lcd.clear()
            lcd.message("day's anime incl")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ay's anime inclu")
            time.sleep(speed)
            lcd.clear()
            lcd.message("y's anime includ")
            time.sleep(speed)
            lcd.clear()
            lcd.message("'s anime include")
            time.sleep(speed)
            lcd.clear()
            lcd.message("s anime includes")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" anime includes ")
            time.sleep(speed)
            lcd.clear()
            lcd.message("anime includes L")
            time.sleep(speed)
            lcd.clear()
            lcd.message("nime includes Lo")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ime includes Lov")
            time.sleep(speed)
            lcd.clear()
            lcd.message("me includes Love")
            time.sleep(speed)
            lcd.clear()
            lcd.message("e includes Love ")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" includes Love i")
            time.sleep(speed)
            lcd.clear()
            lcd.message("includes Love is")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ncludes Love is ")
            time.sleep(speed)
            lcd.clear()
            lcd.message("cludes Love is w")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ludes Love is wa")
            time.sleep(speed)
            lcd.clear()
            lcd.message("udes Love is war")
            time.sleep(speed)
            lcd.clear()
            lcd.message("des Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("es Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("s Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ove is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ve is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("e is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("s war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ar.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("r.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(".")
            time.sleep(speed)
            lcd.clear()
            time.sleep(speed) # Horrible, bloated, and unreadable. Instead there's a new better_motd function
        except KeyboardInterrupt:
            lcd.clear()
            lcd.message("See you!")
            time.sleep(speed)
            lcd.set_backlight(1)
            lcd.clear()
            break
def seeya(): # Funcion to exit the program on ctrl c or whatever you'd like else
    status = False
    lcd.clear()
    lcd.message("See you!")
    time.sleep(2)
    lcd.set_backlight(1)
    lcd.clear()
    sys.exit()
    
def better_motd(word):
    try:
        lcd.set_backlight(0)
        word = " " * 16 + word + " " * 16 # Add padding to keep the scrolling words appart from each other
        for i in range(len(word) - 15): # Using for loop we can make the scrolling of the text easy, manageable and unbloated
            lcd.set_cursor(0, 0)
            lcd.message(word[i:i+16])
            time.sleep(.5) # Notice how much easier it is to read and now you can choose the word you want to display
    except KeyboardInterrupt:
        seeya()
    
if __name__ == "__main__":
    splash()
    try:
        while True: # Example usage cases
            better_motd("Today's anime is love is war.")
            better_motd("NEWS")
            better_motd("Iltalehti: Nyt tuli viimeinen sana ja se on ei")
            better_motd("MTV: Tämän takia kultakorujaan myyvän on syyta olla tarkkana ")
            better_motd("WEATHER")
            better_motd("Tracen academy: -15C")
            better_motd("The hottest umamusume title has been given to Agnes Tachyon. Runners up include Silence Suzuka, Tokai Teio and Symboli Rudolf.")
    except KeyboardInterrupt:
        print("Stopped.")
