import Adafruit_CharLCD as LCD
import time

lcd = LCD.Adafruit_CharLCDBackpack(address=0x21)
speed = 0.5
def splash():
    lcd.set_backlight(0)
    lcd.message("Suzuka Corp.")
    lcd.set_cursor(0, 1)
    lcd.message("(c) 2025")
    time.sleep(2)
    lcd.clear()
    
def motd():
    while True:
        try:
            lcd.clear()
            lcd.set_backlight(0)
            lcd.message("T".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("To".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Tod".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Toda".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today'".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's ".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's a".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's an".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's ani".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anim".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime ".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime i".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("Today's anime in".rjust(16, " "))
            time.sleep(speed)
            lcd.clear()
            lcd.message("oday's anime inc")
            time.sleep(speed)
            lcd.clear()
            lcd.message("day's anime incl")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ay's anime inclu")
            time.sleep(speed)
            lcd.clear()
            lcd.message("y's anime includ")
            time.sleep(speed)
            lcd.clear()
            lcd.message("'s anime include")
            time.sleep(speed)
            lcd.clear()
            lcd.message("s anime includes")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" anime includes ")
            time.sleep(speed)
            lcd.clear()
            lcd.message("anime includes L")
            time.sleep(speed)
            lcd.clear()
            lcd.message("nime includes Lo")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ime includes Lov")
            time.sleep(speed)
            lcd.clear()
            lcd.message("me includes Love")
            time.sleep(speed)
            lcd.clear()
            lcd.message("e includes Love ")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" includes Love i")
            time.sleep(speed)
            lcd.clear()
            lcd.message("includes Love is")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ncludes Love is ")
            time.sleep(speed)
            lcd.clear()
            lcd.message("cludes Love is w")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ludes Love is wa")
            time.sleep(speed)
            lcd.clear()
            lcd.message("udes Love is war")
            time.sleep(speed)
            lcd.clear()
            lcd.message("des Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("es Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("s Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("Love is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ove is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ve is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("e is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("is war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("s war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(" war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("war.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("ar.")
            time.sleep(speed)
            lcd.clear()
            lcd.message("r.")
            time.sleep(speed)
            lcd.clear()
            lcd.message(".")
            time.sleep(speed)
            lcd.clear()
            time.sleep(speed)
        except KeyboardInterrupt:
            lcd.clear()
            lcd.message("See you!")
            time.sleep(speed)
            lcd.set_backlight(1)
            lcd.clear()
            break
def better_motd(word):
    lcd.set_backlight(0)
    word = word  +
    for i in range(len(word))
    
    
if __name__ == "__main__":
    splash()
    better_motd("Today's anime is love is war.")